# Generated by Django 5.0.6 on 2024-10-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_remove_video_user_video_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
